<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://wsdemo.demo.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="HelloWorldServiceImplService" targetNamespace="http://wsdemo.demo.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://wsdemo.demo.com/" elementFormDefault="unqualified" targetNamespace="http://wsdemo.demo.com/" version="1.0">

  <xs:element name="greet" type="tns:greet"/>

  <xs:element name="greetResponse" type="tns:greetResponse"/>

  <xs:complexType name="greet">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="greetResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="greetResponse">
    <wsdl:part element="tns:greetResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="greet">
    <wsdl:part element="tns:greet" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="HelloWorldService">
    <wsdl:operation name="greet">
      <wsdl:input message="tns:greet" name="greet">
    </wsdl:input>
      <wsdl:output message="tns:greetResponse" name="greetResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HelloWorldServiceImplServiceSoapBinding" type="tns:HelloWorldService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="greet">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="greet">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="greetResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HelloWorldServiceImplService">
    <wsdl:port binding="tns:HelloWorldServiceImplServiceSoapBinding" name="HelloWorldServiceImplPort">
      <soap:address location="http://localhost:8080/wsdemo/services/helloWorld"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>